config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|de|fr/ do
    get 'pages/home'
    get 'pages/contact'
    get 'pages/tos'
    get '/faq' => 'pages#faq', as: :faq

    get '/register' => 'users#new', as: :register

    get '/order' => 'orders#show', as: :order
    get '/order/validate/:id', to: 'orders#validate'
    get '/order/execute_payment/:type', to: 'orders#execute_payment', as: :execute_payment
    get '/order/create_payment/:type/:id_pack', to: 'orders#create_payment', as: :create_payment
    get '/order/:id', to: 'orders#show'

    get '/support' => 'support#show', as: :support
    get '/support/ticket/delete/:id', to: 'support#delete_ticket'

    get '/login', to: 'sessions#new', as: :login
    get '/logout', to: 'sessions#destroy', as: :logout

    resources :sessions
    resources :users
    resources :orders

    root 'pages#home'
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :ticket
end

app/models/pack.rb
class Pack < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  has_many :messages
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 32 }, uniqueness: true
  validates :name, presence: true, length: { maximum: 32 }
  validates :surname, presence: true, length: { maximum: 32 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, :on => :create
  has_many :tickets
  after_initialize :defaults

  def defaults
    unless persisted?
      self.tokens=0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery :with => :exception
  before_action :set_locale
  helper_method :current_user


  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={}) # Automatically adds the language to the adress if not set
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_url, alert: t('login.not_authorized') if current_user.nil?
  end
end

app/controllers/orders_controller.rb
require 'paypal-sdk-rest'
include PayPal::SDK::REST

class OrdersController < ApplicationController
  before_action { PayPal::SDK::Core::Config.load('config/paypal.yml',  ENV['RACK_ENV'] || 'development') }

  def show
    if (!params[:id] || !User.exists?(params[:id].to_i))
      redirect_to root_url
      return
    else
      @account = User.find(params[:id].to_i)
      session[:id_to_credit] = params[:id]
    end
  end

  def create_payment
    if !Pack.exists?(params[:id_pack])
      redirect_to root_url
      return
    end

    pack = Pack.find(params[:id_pack])

    if params[:type] == "paypal"
      create_paypal_payment(pack.price, pack.name)
    end

    if params[:type] == "allopass"

    end
  end

  def execute_payment
    if params[:type] == "paypal"
      execute_paypal_payment
    end
  end

  private

  def create_paypal_payment(price, name)
    @payment = PayPal::SDK::REST::Payment.new({
                                                  :intent => "sale",
                                                  :payer => {
                                                      :payment_method => "paypal" },
                                                  :redirect_urls => {
                                                      :return_url => "#{root_url}/order/execute_payment/paypal/",
                                                      :cancel_url => root_url.to_s },
                                                  :transactions => [ {
                                                                         :amount => {
                                                                             :total => price.to_s,
                                                                             :currency => "EUR" },
                                                                         :description => "" } ] } )
    @payment.transactions[0].item_list.items[0] = {
        quantity: "1",
        name: name.to_s,
        price: price.to_s,
        currency: 'EUR',
    }

    if @payment.create
      session[:payment_paypal_id] = @payment.id
      redirect_to @payment.links[1].href
      return
    else
      @payment.error
    end
  end

  def execute_paypal_payment
    if(session.has_key?(:payment_paypal_id) && session.has_key?(:id_to_credit))
      @payment = PayPal::SDK::REST::Payment.find(session[:payment_paypal_id])
      if(@payment.execute( :payer_id => params[:PayerID] ))
        token_quantity = Pack.find_by_name(@payment.transactions[0].item_list.items[0].name.to_s).quantity

        user = User.find(session[:id_to_credit].to_i)
        user.tokens += token_quantity
        user.save
        @validation = t('order.success').html_safe
      else
        @validation = t('order.failure')
      end
    else
      @payment.destroy
      @validation = t('order.time')
      return
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def faq
  end

  def contact
  end

  def tos
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:username])
    user = User.find_by_username(params[:username]) unless user
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: t('login.loggedin')
    else
      flash.now.alert = t('login.invalid')
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: t('login.loggedout')
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  before_action :authorize
  def show
    @ticket = Ticket.new
  end

  def delete_ticket
    ticket = Ticket.find(params[:id].to_i)
    if (ticket && ticket.user_id == current_user.id)
      ticket.resolved = true
      ticket.save!
    end
    redirect_to support_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => t('register.signed_up')
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :name, :surname, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row v-center">
      <div class="col-sm-2">
        <a class="brand" href="#">Hosting project</a>
      </div>
      <div class="col-sm-7">
        <div class="additional-links">
          <%= t('footer.tos').html_safe %>
        </div>
      </div>
      <div class="col-sm-3">
        <h6>The A team</h6>
        <div class="address">
          <%= t('footer.address').html_safe %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Hosting Project', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag "flags/#{I18n.locale}.png" %> <span class="caret"></span></a>
          <ul data-no-turbolink='true' class="dropdown-menu" role="menu">
            <li><%= link_to image_tag('flags/en.png') + ' English', params.merge(:locale => 'en') %></li>
            <li><%= link_to image_tag('flags/de.png') + '  Deutsch', params.merge(:locale => 'de') %></li>
            <li><%= link_to image_tag('flags/fr.png') + '  Français', params.merge(:locale => 'fr') %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to t('navbar.home'), root_path %></a></li>
        <li><a href=""><%= t('navbar.features') %></a></li>
        <li><a href=""><%= t('navbar.prices') %></a></li>
        <% if(!current_user) %>
          <li><%= link_to t('navbar.login'), login_path %></li>
          <li><%= link_to t('navbar.signup'), register_path %></li>
        <% else %>
          <li><%= link_to t('navbar.logout'), logout_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hosting</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'bootstrap.css', :media => 'all' %>
  <%= stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width = device-width, initial-scale = 1.0" />
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</html>

app/views/orders/execute_payment.html.erb
<div class="container">
    <div class="alert alert-success" role="alert"><%= @validation %></div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <% Pack.all.each do |pack| %>
    <p><%= pack.name %></p>
    <p><%= link_to "Buy with Paypal", root_url+"/order/create_payment/paypal/"+pack.id.to_s, class: "btn btn-success" %></p>
  <%end%>
</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
<!-- Slideshow -->
<section id='header'>
  <div class='container'>
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6 title"><%= t('home.community').html_safe %></div>
    </div>
  </div>
</section>

<!-- Login bar -->
<% if (!flash[:notice].nil?) #if there is a notice from any other pages (like register) %>
  <section id='notice'>
    <%= flash[:notice] %>
  </section>
<% elsif current_user.nil? %>
  <section id='login-bar'>
    <div class='container'>
      <%= form_tag sessions_path do %>
        <input type="text" id="username" name="username" class="form-control" placeholder='<%= t('home.login_mail') %>'>
        <input type="password" id="password" name="password" class="form-control" placeholder='<%= t('home.password') %>'>
        <button class="button button-green" type="submit"><%= t('home.login') %></button>
        <button class="button button-red"><%= t('home.register') %></button>
      <% end %>
    </div>
  </section>
<% end %>

<!-- Sneak peek -->
<section id="sneak-peek">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <%= t('home.text').html_safe %>
        <div class="features">
          <div class="box">
            <%= image_tag 'shop/icons/Magic@2x.png', :width => '100', :height => '100' %>
              <%= t('home.easy').html_safe %>
            </p>
          </div>
          <div class="box">
            <%= image_tag 'shop/icons/Responsive1@2x.png', :width => '100', :height => '100' %>
            <%= t('home.appli').html_safe %>
          </div>
          <div class="box">
            <%= image_tag 'shop/icons/Book@2x.png', :width => '100', :height => '100' %>
            <%= t('home.questions').html_safe %>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-sm-offset-2 text-center">
        <div id="sneak-peek_myCarousel" class="carousel slide">
          <div class="carousel-inner">
            <div class="item active">
              <%= image_tag 'shop/home/iPhone.png', :width => '302', :height => '635' %>
            </div>
            <div class="item">
              <%= image_tag 'shop/home/iPhone.png', :width => '302', :height => '635' %>
            </div>
            <div class="item">
              <%= image_tag 'shop/home/iPhone.png', :width => '302', :height => '635' %>
            </div>
          </div>
          <ol class="carousel-indicators">
            <li data-target="#sneak-peek_myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#sneak-peek_myCarousel" data-slide-to="1" class=""></li>
            <li data-target="#sneak-peek_myCarousel" data-slide-to="2" class=""></li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Try it now -->
<section id="try-it-now">
  <div class="container">
    <span><%= t('home.slogan') %></span>
    <a class="btn btn-large btn-danger" href="#"><%= t('home.try') %></a>
  </div>
</section>

app/views/pages/tos.html.erb
<h1>Pages#tos</h1>
<p>Find me in app/views/pages/tos.html.erb</p>

app/views/support/home.html.erb
<script>
function New()
{
var div = document.getElementById("new");
    if(div.style.display == "none")
    {
        div.style.display = "";
    }
    else
    {
        div.style.display = "none";
    }
}
</script>

<h1>This is the support, biatch !</h1>
<a href="javascript: New()" class="btn btn-primary btn-warning">Open a ticket !</a>

<div id="new" style="display: none;">
  <h5>Ouverture de ticket</h5>
</div>
<br><br>

<h5>Liste de vos ticket(s) non résolus :</h5>
<%Ticket.where(user_id: current_user, resolved: false).all.each do |ticket|%>
    <a href="<%= "/support/ticket/delete/#{ticket.id}" %>" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span> Résolu</a>
    <%= ticket.title %> <br>
<%end%>


<h5>Liste de vos ticket(s) résolus :</h5>
<%Ticket.where(user_id: current_user, resolved: true).all.each do |ticket|%>
    <%= ticket.title %> <br>
<%end%>

app/views/support/show.html.erb
<script>
function New()
{
var div = document.getElementById("new");
    if(div.style.display == "none")
    {
        div.style.display = "";
    }
    else
    {
        div.style.display = "none";
    }
}
</script>

<h1>This is the support, biatch !</h1>
<a href="javascript: New()" class="btn btn-primary btn-warning">Open a ticket !</a>

<div id="new" style="display: none;">
  <h5>Ouverture de ticket</h5>
</div>
<br><br>

<h5>Liste de vos ticket(s) non résolus :</h5>
<%Ticket.where(user_id: current_user, resolved: false).all.each do |ticket|%>
    <a href="<%= "/support/ticket/delete/#{ticket.id}" %>" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span> Résolu</a>
    <%= ticket.title %> <br>
<%end%>


<h5>Liste de vos ticket(s) résolus :</h5>
<%Ticket.where(user_id: current_user, resolved: true).all.each do |ticket|%>
    <%= ticket.title %> <br>
<%end%>

app/views/user/new.html.erb
<section id="register-title">
  <p>Create your account now</p>
</section>

<section id="register-content">
  <div class='container'>
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= form_for :user do |f|  %>
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
            <%= f.text_field  :username, class:'form-control', placeholder: 'Username' %>
          </div>
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <%= f.text_field :password, type: 'password', class:'form-control', placeholder: 'Password' %>
          </div>
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <%= f.text_field :password, type: 'password', class:'form-control', placeholder: 'Password confirmation' %>
          </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
           <%= f.text_field  :email, class:'form-control', placeholder: 'Email'  %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
          <%= f.text_field  :name, class:'form-control', placeholder:'Name' %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
          <%= f.text_field  :surname, class:'form-control', placeholder: 'Surname' %>
        </div>
        <div class="button-group">
          <%= f.submit 'Register', class: "btn btn-primary" %>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<% if(@user.errors.any?) %>
  <section id="register-error">
    <p><%= t('register.errors') %></p>
    <% for message in @user.errors.full_messages %>
      <li><%= message %></li>
    <% end %>
  </section>
<% else %>
  <section id="register-title">
    <p><%= t('register.create') %></p>
  </section>
<% end %>

<section id="register-content">
  <div class='container'>
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= form_for @user do |f|  %>
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
            <%= f.text_field  :username, class:'form-control', placeholder: t('register.username')%>
          </div>
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <%= f.text_field :password, type: 'password', class:'form-control', placeholder: t('register.password') %>
          </div>
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <%= f.text_field :password_confirmation, type: 'password', class:'form-control', placeholder: t('register.confirmation') %>
          </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
           <%= f.text_field  :email, class:'form-control', placeholder: t('register.email')  %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
          <%= f.text_field  :name, class:'form-control', placeholder: t('register.name') %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
          <%= f.text_field  :surname, class:'form-control', placeholder: t('register.surname') %>
        </div>
        <div class="button-group">
          <%= f.submit t('register.register'), class: "btn btn-primary" %>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>